"""Add profile_picture column to users table

Revision ID: c3f8a1b2d4e5
Revises: a4a2f39217a7
Create Date: 2026-09-25 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f8a1b2d4e5'
down_revision = 'a4a2f39217a7'
branch_labels = None
depends_on = None


def upgrade():
    # The column may already exist if the DB was created by db.create_all()
    # instead of migrations. Check before adding to avoid errors.
    conn = op.get_bind()
    columns = [col['name'] for col in sa.inspect(conn).get_columns('users')]
    if 'profile_picture' not in columns:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
    # ### end Alembic commands ###
